"""
tools.py - Part 2 / Task 6

check_job_application_status(record_id) looks up one application in the
dataset generated by dataset.py and returns its status, expected salary and a
DESIGNED escalation score.

--------------------------------------------------------------------------
ESCALATION SCORE - EXACT FORMULA
--------------------------------------------------------------------------

    recency_norm      = min(days_since_created / DAYS_P80, 1.0)
    escalation_score  = W_FLAG * flagged_priority_review + W_AGE * recency_norm

with

    W_FLAG   = 0.60
    W_AGE    = 0.40
    DAYS_P80 = 23.0

DAYS_P80 is not a guess: it is the 80th percentile of days_since_created in the
48 records that dataset.py generates at seed 20260828 (p50 = 13.5, p80 = 23.0,
p90 = 27.3, printed by `python dataset.py`). Normalising by p80 rather than by
the raw maximum of 30 means the age term saturates at the point where an
application has already been sitting longer than 80% of the queue, instead of
only saturating at the single oldest record.

This is deliberately NOT a bare boolean OR of the two signals. The weights make
the two inputs interact:

    flagged, any age          -> 0.60 .. 1.00
    unflagged, at/over p80    -> 0.40
    unflagged, at p50 (13.5d) -> 0.235
    unflagged, brand new      -> 0.00

--------------------------------------------------------------------------
RECOMMENDED ESCALATION THRESHOLD = 0.40
--------------------------------------------------------------------------

Escalate when escalation_score >= 0.40. Justified against this dataset's own
distribution: 0.40 is exactly the score an UNFLAGGED application reaches when
days_since_created hits 23.0, the 80th percentile of the generated data. So the
rule reads, in business terms:

    escalate every application the recruiter has already flagged for priority
    review (they clear 0.60 on the flag alone), plus the slowest-moving fifth
    of the unflagged queue.

On the generated dataset this selects 17 of the 48 records (35.42%): all 7
flagged records, plus the 10 unflagged records that have been sitting 23 days
or longer. The score itself runs 0.0000 .. 1.0000 with mean 0.3234, so the
threshold cuts the distribution well above its mean and leaves a review queue
small enough for a human support desk to actually work through.
"""

from typing import Dict

from dataset import JOB_APPLICATIONS, days_percentile, get_record

# weights and the normalisation constant documented above
W_FLAG = 0.60
W_AGE = 0.40
DAYS_P80 = 23.0

ESCALATION_THRESHOLD = 0.40


def compute_escalation_score(flagged: bool, days_since_created: int) -> float:
    """Designed escalation score in [0, 1]. See the module docstring."""
    recency_norm = min(days_since_created / DAYS_P80, 1.0)
    score = W_FLAG * (1.0 if flagged else 0.0) + W_AGE * recency_norm
    return round(min(1.0, max(0.0, score)), 4)


def check_job_application_status(record_id: str) -> Dict:
    """Look up a Naukri.com job application by its record id.

    Returns the application's current pipeline status, the candidate's expected
    annual salary in INR, and a designed escalation score in [0, 1] that
    combines the recruiter's priority-review flag with how long the application
    has been sitting in the queue.

    Args:
        record_id: the application identifier, for example "NAU-1003".

    Returns:
        A dict with keys: found, record_id, status, expected_salary_inr,
        days_since_created, flagged_priority_review, escalation_score,
        escalation_threshold, escalate, and explanation. When the id does not
        exist, found is False and an error message is returned instead.
    """
    record = get_record(record_id)
    if record is None:
        return {
            "found": False,
            "record_id": record_id,
            "error": (f"No job application found with record_id '{record_id}'. "
                      f"Valid ids look like NAU-1000 .. NAU-1047."),
        }

    flagged = record["flagged_priority_review"]
    days = record["days_since_created"]
    score = compute_escalation_score(flagged, days)
    recency_norm = round(min(days / DAYS_P80, 1.0), 4)
    escalate = score >= ESCALATION_THRESHOLD

    explanation = (
        f"escalation_score = {W_FLAG} * flagged({int(flagged)}) + "
        f"{W_AGE} * min({days}/{DAYS_P80}, 1.0)={recency_norm} = {score}; "
        f"threshold {ESCALATION_THRESHOLD} -> "
        f"{'ESCALATE' if escalate else 'no escalation'}"
    )

    return {
        "found": True,
        "record_id": record["record_id"],
        "category": record["category"],
        "status": record["status"],
        "expected_salary_inr": record["expected_salary_inr"],
        "days_since_created": days,
        "flagged_priority_review": flagged,
        "recency_norm": recency_norm,
        "escalation_score": score,
        "escalation_threshold": ESCALATION_THRESHOLD,
        "escalate": escalate,
        "explanation": explanation,
    }


def _demo():
    print("=" * 78)
    print("PART 2 / TASK 6 - check_job_application_status + escalation score")
    print("=" * 78)
    print(f"formula   : escalation_score = {W_FLAG}*flagged + "
          f"{W_AGE}*min(days/{DAYS_P80}, 1.0)")
    print(f"threshold : {ESCALATION_THRESHOLD}")
    print(f"DAYS_P80  : {DAYS_P80}  (measured 80th percentile of "
          f"days_since_created = {days_percentile(80):.1f})")
    print(f"            p50 = {days_percentile(50):.1f}, "
          f"p90 = {days_percentile(90):.1f}")
    print()

    print("--- four representative lookups ---")
    # pick one flagged-new, one flagged-old, one unflagged-old, one unflagged-new
    flagged = [r for r in JOB_APPLICATIONS if r["flagged_priority_review"]]
    unflagged = [r for r in JOB_APPLICATIONS if not r["flagged_priority_review"]]
    picks = [
        min(flagged, key=lambda r: r["days_since_created"])["record_id"],
        max(flagged, key=lambda r: r["days_since_created"])["record_id"],
        max(unflagged, key=lambda r: r["days_since_created"])["record_id"],
        min(unflagged, key=lambda r: r["days_since_created"])["record_id"],
    ]
    for rid in picks:
        res = check_job_application_status(rid)
        print(f"\n{rid}  [{res['category']}]")
        print(f"  status              : {res['status']}")
        print(f"  expected_salary_inr : {res['expected_salary_inr']:,}")
        print(f"  days_since_created  : {res['days_since_created']}")
        print(f"  flagged             : {res['flagged_priority_review']}")
        print(f"  escalation_score    : {res['escalation_score']}")
        print(f"  escalate            : {res['escalate']}")
        print(f"  {res['explanation']}")

    print("\n--- unknown id ---")
    print(check_job_application_status("NAU-9999"))

    print("\n--- distribution of the designed score over all 48 records ---")
    scores = [compute_escalation_score(r["flagged_priority_review"],
                                       r["days_since_created"])
              for r in JOB_APPLICATIONS]
    n_esc = sum(1 for s in scores if s >= ESCALATION_THRESHOLD)
    print(f"  min={min(scores):.4f}  max={max(scores):.4f}  "
          f"mean={sum(scores)/len(scores):.4f}")
    print(f"  records at/over threshold {ESCALATION_THRESHOLD}: "
          f"{n_esc}/{len(scores)} ({100.0*n_esc/len(scores):.2f}%)")
    print(f"  of which flagged: "
          f"{sum(1 for r in JOB_APPLICATIONS if r['flagged_priority_review'])}")


if __name__ == "__main__":
    _demo()
